### ISSUE TITLE
Support VS 2015

### ISSUE THREAD

**Issue by dail8859** [dail8859/cookiecutter-npp-cpp-plugin#1]

**Comment by Ekopalypse** [comment]
Curious about this one - as of my understanding [this](https://github.com/dail8859/cookiecutter-npp-cpp-plugin/blob/master/%7B%7Bcookiecutter.plugin_slug%7D%7D/%7B%7Bcookiecutter.plugin_slug%7D%7D.sln#L3) indicates that it is VS2015 (would be 15 for VS2017). ([VS version numbers <= 2015](https://omwtm.blog/2014/12/03/visual-studio-2013-version-numbers-and-updates/) and [VS2017 versioning](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#-visual-studio-2017-version-15914-))

By the way, thx for the fast fix. It would have never came into my mind that this &editor ... was the issue.

**Comment by dail8859** [comment]
All I know is 2017 works fine (since that is what I use). That's not to say it is currently done correctly and I'm not sure if some things would need changed for 2015 (such as platform toolset, etc).

**Comment by Ekopalypse** [comment]
I will give it a try to install VS2015 in a virtual environment and will do a test.
Will probably take 1-2 days but report back here.

**Comment by dail8859** [comment]
Appreciate the help. No rush at all.

**Comment by Ekopalypse** [comment]
You are right, the toolset needs to be a choice but I'm not sure if the wording is correct but maybe not worth thinking about it at all!?
So what I did is using choice field like this
```
plugin_name [My Plugin]: test2
plugin_slug [test2]:
description [My very first plugin for Notepad++]:
full_name [John Smith]: ekopalypse
email [john.smith@email.com]: ekopalypse@gmail.com
npp_path_x86 [C:\Program Files (x86)\Notepad++]: C:\tools\Npp\771\x32
npp_path_x64 [C:\Program Files\Notepad++]: C:\tools\Npp\771\x64
Select toolset:
1 - VS2017
2 - VS2015
Choose from 1, 2 (1, 2) [1]: 2
```
and this build the .vcxproj with

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet><PlatformToolset>v140</PlatformToolset></PropertyGroup>
...
```

As you see, it isn't 100% nice as it didn't add the necessary eols to look more like expected

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'" Label="Configuration">
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet>
    <PlatformToolset>v140</PlatformToolset>
  </PropertyGroup>
...
```

If you are ok with it I would do a PR as I'm not sure if this is something which can be easily changed.
I need to investigate. (and maybe do another PR once I found out how to do this?)

UPDATE:
Ok, it isn't an issue as cookiecutter understands the one liner if statement, so code like

`{{141 if cookiecutter.toolset == "VS2017" else 140 }}`

works :-)
The only open question is how to call the choice, toolset, VSCompiler, VSVersion ... :-)

**Comment by dail8859** [comment]
Apologies for the delayed response.

> Ok, it isn't an issue as cookiecutter understands the one liner if statement, so code like

Yep, they use jinja2 templates so it provides quite a bit of flexibility.

> The only open question is how to call the choice, toolset, VSCompiler, VSVersion ... :-)

Don't think it matters too much in the in. `VSVersion` would probably be my preference.

**Comment by Ekopalypse** [comment]
>Apologies for the delayed response.

Nothing to apologize, I know that we all do this just for fun and that we have real life :-)
