### ISSUE TITLE
Editor instance doesn't change

### ISSUE THREAD

**Issue by Ekopalypse** [dail8859/cookiecutter-npp-cpp-plugin#2]
Sorry, this is not really a template generation code issue but rather an issue
within the provided example code. If you want to close it because this is something the plugin
dev should do, then I'm fine with it.
The issue is, that the editor instance is always editor2 and does not change to editor1 as
editor1 gets overwritten by editor2 (at least that is my conclusion).
Sorry, I haven't figured out what is causing it but to replicate,
start npp via VS and make sure both views are used,
then set a breakpoint in the beNotified function.
Click into npp and recheck editor1 and editor2 objects - they are the same.

**Comment by dail8859** [comment]
> but rather an issue within the provided example code.

Yes definitely a bug that needs fixed.
