### ISSUE TITLE
Possibility to use portable npp versions as well

### ISSUE THREAD

**Issue by Ekopalypse** [dail8859/cookiecutter-npp-cpp-plugin#4]
Would you consider an additional field, maybe npp_full_path, to offer the ability to copy the created dlls into a portable npp directory?
Maybe some choice field which asks for x64 and x86 projects as well?
Wouldn't mind to work on it.

**Comment by dail8859** [comment]
> Would you consider an additional field, maybe npp_full_path, to offer the ability to copy the created dlls into a portable npp directory?

Being able to specify a Notepad++ installation directory seems reasonable. This directory would be used for copying the plugin and for launching the `notepad++.exe` for debugging. And as a default this can just be the normal installation directories. 

> Maybe some choice field which asks for x64 and x86 projects as well?

I think by default creating both x64 and x86 projects is fine. Id assume this needed for 98% of the use-cases and if someone had a particular reason for not wanting one of them then they probably know enough to remove it themselves.

> Wouldn't mind to work on it.

Pull requests are always welcome :)

**Comment by Ekopalypse** [comment]
Thx - I'm on it.

**Comment by dail8859** [comment]
Closed by 3bf5056
